services: 

  #SQL SERVER1 - this will be what we monitor
  sqlserver1:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver         
    container_name: sqlserver2022_01
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}      
      - TELEGRAF_SQL_SERVER_PASSWORD=${TELEGRAF_SQL_SERVER_PASSWORD}  
    ports:
      - "1433:1433"
    volumes:
      - ./container-data/sqlserver2022_01/data:/var/opt/mssql/data
      - ./container-data/sqlserver2022_01/data:/var/opt/mssql/log   
    #bring up all monitoring services first
    depends_on:
      - timescaledb
      - telegraf
      - grafana
      - influxdb

  #SQL SERVER2 - this will be what we monitor
  sqlserver2:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver      
    container_name: sqlserver2022_02
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}      
      - TELEGRAF_SQL_SERVER_PASSWORD=${TELEGRAF_SQL_SERVER_PASSWORD}  
    ports:
      - "2433:1433"
    volumes:
      - ./container-data/sqlserver2022_02/data:/var/opt/mssql/data
      - ./container-data/sqlserver2022_02/data:/var/opt/mssql/log   
    #bring up all monitoring services first
    depends_on:
      - timescaledb
      - telegraf
      - grafana
      - influxdb

  #workload generator1
  workload1:
    build:
      context: .
      dockerfile: Dockerfile.workload
      args:
        WORKLOAD_DATABASE_SERVER: sqlserver2022_01
        WORKLOAD_DATABASE: demo_workload
        SQL_SA_USERNAME: sa
        SQL_SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
        WORKLOAD_SERVER_PORT: 1433
        MAX_PARALLEL_WORKLOADS: 1000
    container_name: workload1    
    depends_on:
      - sqlserver1

  #workload generator2
  workload2:
    build:
      context: .
      dockerfile: Dockerfile.workload
      args:
        WORKLOAD_DATABASE_SERVER: sqlserver2022_02
        WORKLOAD_DATABASE: demo_workload
        SQL_SA_USERNAME: sa
        SQL_SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
        WORKLOAD_SERVER_PORT: 1433
        MAX_PARALLEL_WORKLOADS: 500
    container_name: workload2    
    depends_on:
      - sqlserver2

  #TIMESCALEDB - this will be the database where we store the metrics
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=${TIMESCALEDB_POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./container-data/timescaledb/data:/var/lib/postgresql/data
  
  #INFLUXDB - this will be the database where we store the metrics
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - ./container-data/influxdb/data:/var/lib/influxdb

  #TELEGRAF - this will be the agent that collects the metrics
  telegraf:
    build:
      context: .
      dockerfile: Dockerfile.telegraf
      args:
        TIMESCALEDB_POSTGRES_PASSWORD: ${TIMESCALEDB_POSTGRES_PASSWORD}
        TELEGRAF_SQL_SERVER_PASSWORD: ${TELEGRAF_SQL_SERVER_PASSWORD}
    container_name: telegraf

  #GRAFANA - this will be the dashboard where we visualize the metrics
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./container-data/grafana/data:/var/lib/grafana
    depends_on:
      - timescaledb
      - telegraf
      - influxdb