global:
  scrape_interval: 15s  # How often to scrape targets by default.
  evaluation_interval: 15s  # How often to evaluate rules.

# Alerting configuration (optional, can be customized)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Example scrape target for a Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Example scrape target for a custom application
  - job_name: "custom_app"
    static_configs:
      - targets: ["custom-app:8080"]

  # Scrape metrics from Telegraf
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]  # Replace "telegraf" with the hostname or IP of your Telegraf instance